version: '3'
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 5000:5000
    links:
      - mongo
      
  mongo:
    image: mongo:latest
    hostname: mongodb
    environment:
      MONGO_INITDB_DATABASE: my_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - moje_data:/data/db
    
volumes:
  moje_data:
